routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin/', 'as'=>'admin.','middleware' => ['auth','auth-custom']],function (){

    Route::get('dashboard',              ['as'=>'dashboard','uses' => 'Admin\DashboardController@index']);

    Route::get('user',                   ['as'=>'user','uses' => 'Admin\UserController@index']);
    Route::get('user/add',               ['as'=>'user.add','uses' => 'Admin\UserController@add']);
    Route::post('user/store',            ['as'=>'user.store','uses' => 'Admin\UserController@store']);
    Route::get('user/edit/{id}',         ['as'=>'user.edit','uses' => 'Admin\UserController@edit']);
    Route::post('user/update/{id}',      ['as'=>'user.update','uses' => 'Admin\UserController@update']);
    Route::get('user/delete/{id}',       ['as'=>'user.delete','uses' => 'Admin\UserController@delete']);
    Route::get('user/password-reset',    ['as'=>'user.password-reset','uses' => 'Admin\UserController@passwordReset']);
    Route::post('user/password-reset',   ['as'=>'user.password-reset.update','uses' => 'Admin\UserController@passwordUpdate']);

    Route::get('site-profile/edit',      ['as'=>'site-profile.edit','uses' => 'Admin\SiteProfileController@edit']);
    Route::post('site-profile/update',   ['as'=>'site-profile.update','uses' => 'Admin\SiteProfileController@update']);

    Route::get('category',                   ['as'=>'category','uses' => 'Admin\CategoryController@index']);
    Route::get('category/add',               ['as'=>'category.add','uses' => 'Admin\CategoryController@add']);
    Route::post('category/store',            ['as'=>'category.store','uses' => 'Admin\CategoryController@store']);
    Route::get('category/edit/{id}',         ['as'=>'category.edit','uses' => 'Admin\CategoryController@edit']);
    Route::post('category/update/{id}',      ['as'=>'category.update','uses' => 'Admin\CategoryController@update']);
    Route::get('category/delete/{id}',       ['as'=>'category.delete','uses' => 'Admin\CategoryController@delete']);

    Route::get('news',                   ['as'=>'news','uses' => 'Admin\NewsController@index']);
    Route::get('news/add',               ['as'=>'news.add','uses' => 'Admin\NewsController@add']);
    Route::post('news/store',            ['as'=>'news.store','uses' => 'Admin\NewsController@store']);
    Route::get('news/edit/{id}',         ['as'=>'news.edit','uses' => 'Admin\NewsController@edit']);
    Route::post('news/update/{id}',      ['as'=>'news.update','uses' => 'Admin\NewsController@update']);
    Route::get('news/delete/{id}',       ['as'=>'news.delete','uses' => 'Admin\NewsController@delete']);
});
// part 8 1.45.12 mins completed
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\PasswordResetFormValidation;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//       $users=User::select('id','email','created_at','status');
        $users = DB::table('users')->select('id','username','email','contact_no','created_at','status')->get();
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function add()
    {
        return view('admin.user.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
//    public function store(AddFormValidation $request)
//    {
//        $request->request->add(['status' => $request->get('status')=='active'?1:0]);
//    User::create($request->all());
//    $request->session()->flash('success_message','User added Successfully');
//    return redirect()->route('admin.user');
//    }

    public function store(Request $request)
    {
       $request -> validate([
          'username' => 'required',
          'email' => 'required',
          'password' => 'required',
//          'full_name' => 'required',
//          'contact_no' => 'required',
          'address' => 'required',
//          'status' => 'required',
       ]);
       $user = new User();
       $user -> username = $request->get('username');
       $user -> email = $request->get('email');
       $user -> password = $request->get('password');
       $user -> full_name = $request->get('fullname');
       $user -> contact_no = $request->get('contact');
       $user -> address = $request->get('address');
//       $user -> status = $request->get('status') == 'active'?1:0;
       $user -> save();
       return redirect()->route('admin.user');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $request -> validate([
            'username' => 'required',
            'email' => 'required',
            'password' => 'required',
//          'full_name' => 'required',
//          'contact_no' => 'required',
            'address' => 'required',
//          'status' => 'required',
        ]);
        $user = User::find($id);
        $user -> username = $request->get('username');
        $user -> email = $request->get('email');
        $user -> password = $request->get('password');
        $user -> full_name = $request->get('fullname');
        $user -> contact_no = $request->get('contact');
        $user -> address = $request->get('address');
        $user -> save();
        return redirect()->route('admin.user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $user = User::find($id);
        $user -> delete();
        return redirect()->route('admin.user');
    }

    public function passwordReset()
    {
        return view('admin.user.password_reset');
    }

    public function passwordUpdate(PasswordResetFormValidation $request)
    {
//        dd($request->all());
    $user = auth()->user();
    $user -> password = bcrypt($request->get('password'));
    $user -> save();
//    $request->session()->flash('success_message','Password reset successfully');
    return redirect()->route('admin.user')->with('message', 'IT WORKS!');
    }
}

resources/views/admin/user/add.blade.php
@extends('admin.layout.master')

@section('content')

    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">Home</a>
                    </li>

                    <li>
                        <a href="#">Tables</a>
                    </li>
                    <li class="active">Simple &amp; Dynamic</li>
                </ul><!-- /.breadcrumb -->

                <div class="nav-search" id="nav-search">
                    <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
                    </form>
                </div><!-- /.nav-search -->
            </div>

            <div class="page-content">
                <div class="page-header">
                    <h1>
                        Tables
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                            Static &amp; Dynamic Tables
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                    @endif
                        <!-- PAGE CONTENT BEGINS -->
                        <form action="{{route('admin.user.store')}}" class="form-horizontal" role="form" method="post">
                            @csrf
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Username </label>

                                <div class="col-sm-9">
                                    <input type="text" name="username" id="" placeholder="Username" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Email address </label>

                                <div class="col-sm-9">
                                    <input type="email" name="email" id="" placeholder="email" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Password </label>

                                <div class="col-sm-9">
                                    <input type="password" name="password" id="" placeholder="Password" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Full name </label>

                                <div class="col-sm-9">
                                    <input type="text" name="fullname" id="" placeholder="Full name" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Contact number </label>

                                <div class="col-sm-9">
                                    <input type="number" name="contact" id="" placeholder="Phone number" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Address </label>

                                <div class="col-sm-9">
                                    <textarea type="text" rows="10" cols="10" name="address" placeholder="Address" class="col-xs-10 col-sm-5"></textarea>
                                </div>
                            </div>

                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">
                                        <i class="ace-icon fa fa-check bigger-110"></i>
                                        Submit
                                    </button>

                                    &nbsp; &nbsp; &nbsp;
                                    <button class="btn" type="reset">
                                        <i class="ace-icon fa fa-undo bigger-110"></i>
                                        Reset
                                    </button>
                                </div>
                            </div>
                        </form>

                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->


    @endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layout.master')

@section('content')

    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">Home</a>
                    </li>

                    <li>
                        <a href="#">Tables</a>
                    </li>
                    <li class="active">Simple &amp; Dynamic</li>
                </ul><!-- /.breadcrumb -->

                <div class="nav-search" id="nav-search">
                    <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
                    </form>
                </div><!-- /.nav-search -->
            </div>

            <div class="page-content">
                <div class="page-header">
                    <h1>
                        Tables
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                            Static &amp; Dynamic Tables
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                    @endif
                        <!-- PAGE CONTENT BEGINS -->
                        <form action="{{route('admin.user.update',$user->id)}}" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('POST')
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Username </label>

                                <div class="col-sm-9">
                                    <input type="text" name="username" id="" placeholder="Username" class="col-xs-10 col-sm-5" value="{{$user->username}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Email address </label>

                                <div class="col-sm-9">
                                    <input type="email" name="email" id="" placeholder="email" class="col-xs-10 col-sm-5" value="{{$user->email}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Password </label>

                                <div class="col-sm-9">
                                    <input type="password" name="password" id="" placeholder="Password" class="col-xs-10 col-sm-5" value="{{$user->password}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Full name </label>

                                <div class="col-sm-9">
                                    <input type="text" name="fullname" id="" placeholder="Full name" class="col-xs-10 col-sm-5" value="{{$user->full_name}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Contact number </label>

                                <div class="col-sm-9">
                                    <input type="number" name="contact" id="" placeholder="Phone number" class="col-xs-10 col-sm-5" value="{{$user->contact_no}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Address </label>

                                <div class="col-sm-9">
                                    <input type="text" name="address" id="" placeholder="Address" class="col-xs-10 col-sm-5" value="{{$user->address}}">
                                </div>
                            </div>

                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">
                                        <i class="ace-icon fa fa-check bigger-110"></i>
                                        Submit
                                    </button>

                                    &nbsp; &nbsp; &nbsp;
                                    <button class="btn" type="reset">
                                        <i class="ace-icon fa fa-undo bigger-110"></i>
                                        Reset
                                    </button>
                                </div>
                            </div>
                        </form>

                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->


    @endsection

resources/views/admin/user/password_reset.blade.php
@extends('admin.layout.master')

@section('content')

    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">Home</a>
                    </li>

                    <li>
                        <a href="#">Profile</a>
                    </li>
                    <li class="active">Password Reset</li>
                </ul><!-- /.breadcrumb -->

                <div class="nav-search" id="nav-search">
                    <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
                    </form>
                </div><!-- /.nav-search -->
            </div>

            <div class="page-content">
                <div class="page-header">
                    <h1>
                        Profile
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                            Password Reset
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        @if(session()->has('message'))
                            <div class="alert alert-success">
                                {{ session()->get('message') }}
                            </div>
                    @endif
                        <!-- PAGE CONTENT BEGINS -->
                        <form action="{{route('admin.user.password-reset.update')}}" class="form-horizontal" role="form" method="post">
                            @csrf
                            <div class="form-group {{ $errors->has('password') }}">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Password </label>

                                <div class="col-sm-9">
                                    <input type="password" name="password" placeholder="Password" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="form-group {{ $errors->has('password_confirmation') }}">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Confirm Password </label>

                                <div class="col-sm-9">
                                    <input type="password" name="password_confirmation" placeholder="Confirm Password" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">
                                        <i class="ace-icon fa fa-check bigger-110"></i>
                                        Submit
                                    </button>

                                    &nbsp; &nbsp; &nbsp;
                                    <button class="btn" type="reset">
                                        <i class="ace-icon fa fa-undo bigger-110"></i>
                                        Reset
                                    </button>
                                </div>
                            </div>
                        </form>

                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->


    @endsection

resources/views/admin/user/test.blade.php
<ul class="nav nav-list">
        <li {!! request()->is('admin/dashboard')?'class="active"':'' !!}>
            <a href="{{route('admin.dashboard')}}">
                <i class="menu-icon fa fa-tachometer"></i>
                <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
        </li>

        <li class="">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-desktop"></i>
                <span class="menu-text">
								UI &amp; Elements
							</span>

                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
                <li class="">
                    <a href="#" class="dropdown-toggle">
                        <i class="menu-icon fa fa-caret-right"></i>

                        Layouts
                        <b class="arrow fa fa-angle-down"></b>
                    </a>

                    <b class="arrow"></b>

                    <ul class="submenu">
                        <li class="">
                            <a href="top-menu.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Top Menu
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="two-menu-1.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Two Menus 1
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="two-menu-2.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Two Menus 2
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="mobile-menu-1.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Default Mobile Menu
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="mobile-menu-2.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Mobile Menu 2
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="mobile-menu-3.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Mobile Menu 3
                            </a>

                            <b class="arrow"></b>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul><!-- /.nav-list -->