routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin/', 'as'=>'admin.','middleware' => ['auth','auth-custom']],function (){

    Route::get('dashboard',              ['as'=>'dashboard','uses' => 'Admin\DashboardController@index']);

    Route::get('user',                   ['as'=>'user','uses' => 'Admin\UserController@index']);
    Route::get('user/add',               ['as'=>'user.add','uses' => 'Admin\UserController@add']);
    Route::post('user/store',            ['as'=>'user.store','uses' => 'Admin\UserController@store']);
    Route::get('user/edit/{id}',         ['as'=>'user.edit','uses' => 'Admin\UserController@edit']);
    Route::post('user/update/{id}',      ['as'=>'user.update','uses' => 'Admin\UserController@update']);
    Route::get('user/delete/{id}',       ['as'=>'user.delete','uses' => 'Admin\UserController@delete']);
    Route::get('user/password-reset',    ['as'=>'user.password-reset','uses' => 'Admin\UserController@passwordReset']);
    Route::post('user/password-reset',   ['as'=>'user.password-reset.update','uses' => 'Admin\UserController@passwordUpdate']);

    Route::get('site-profile/edit',      ['as'=>'site-profile.edit','uses' => 'Admin\SiteProfileController@edit']);
    Route::post('site-profile/update',   ['as'=>'site-profile.update','uses' => 'Admin\SiteProfileController@update']);

    Route::get('category',                   ['as'=>'category','uses' => 'Admin\CategoryController@index']);
    Route::get('category/add',               ['as'=>'category.add','uses' => 'Admin\CategoryController@add']);
    Route::post('category/store',            ['as'=>'category.store','uses' => 'Admin\CategoryController@store']);
    Route::get('category/edit/{id}',         ['as'=>'category.edit','uses' => 'Admin\CategoryController@edit']);
    Route::post('category/update/{id}',      ['as'=>'category.update','uses' => 'Admin\CategoryController@update']);
    Route::get('category/delete/{id}',       ['as'=>'category.delete','uses' => 'Admin\CategoryController@delete']);

    Route::get('news',                   ['as'=>'news','uses' => 'Admin\NewsController@index']);
    Route::get('news/add',               ['as'=>'news.add','uses' => 'Admin\NewsController@add']);
    Route::post('news/store',            ['as'=>'news.store','uses' => 'Admin\NewsController@store']);
    Route::get('news/edit/{id}',         ['as'=>'news.edit','uses' => 'Admin\NewsController@edit']);
    Route::post('news/update/{id}',      ['as'=>'news.update','uses' => 'Admin\NewsController@update']);
    Route::get('news/delete/{id}',       ['as'=>'news.delete','uses' => 'Admin\NewsController@delete']);
});
// part 8 1.45.12 mins completed
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = 'news';
    protected $fillable = ['title','slug','image','writer','short_desc','detail_desc','publish_date','status'];
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;
use App\News;
use Illuminate\Support\Str;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class NewsController extends AdminBaseController
{
    protected $view_path = 'admin.news';
    protected $base_route = 'admin.news';
    protected $panel = 'News';
    public function index()
    {
//       $categories=Category::select('title','slug','image','status');
//       dd($categories);
        $news = DB::table('news')->select('id','title','slug','image','writer','short_desc','detail_desc','publish_date','status')->get();
        return view(parent::loadDataToView($this->view_path.'.index'),compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function add()
    {
        return view(parent::loadDataToView($this->view_path.'.add'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request->all());
        $request -> validate([
            'title' => 'required',
//            'image' => 'required',
//            'status' => 'required',

        ]);
        $news = new News();
        $news -> title = $request->get('title');
        $news -> slug = Str::slug($request->get('title'));
        if($request->hasfile('image')){
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = time().'.'.$extension;
            $file -> move('uploads/news/', $filename);
            $news->image = $filename;
        }else{
//            return $request;
            $news->image = '';
        }

        $news -> writer = $request->get('writer');
        $news -> short_desc = $request->get('short_desc');
        $news -> detail_desc = $request->get('detail_desc');
        $news -> publish_date = $request->get('date');
//        return $request;
        $news -> status = $request->get('status') == 'active'?1:0;
        $news -> save();
        return redirect()->route($this->base_route);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = News::find($id);
        return view($this->view_path.'.edit',compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $request -> validate([
            'title' => 'required',
//          'status' => 'required',
        ]);
        $news = News::find($id);
        $news -> title = $request->get('title');
        if($request->hasfile('image')){
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = time().'.'.$extension;
            $file -> move('uploads/news/', $filename);
            $news->image = $filename;
        }
        $news -> save();
        return redirect()->route($this->base_route);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $news= News::find($id);
        $news -> delete();
        return redirect()->route($this->base_route);
    }
}

resources/views/admin/news/add.blade.php
@extends('admin.layout.master')

@section('css')
    <link rel="stylesheet" href="{{asset('admin-panel/assets/css/bootstrap-datepicker3.min.css')}}" />
    @endsection

@section('content')

    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">Home</a>
                    </li>

                    <li>
                        <a href="#">News</a>
                    </li>
                    <li class="active">Add News</li>
                </ul><!-- /.breadcrumb -->

                <div class="nav-search" id="nav-search">
                    <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
                    </form>
                </div><!-- /.nav-search -->
            </div>

            <div class="page-content">
                <div class="page-header">
                    <h1>
                        Category
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                            Add
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                    @endif
                        <!-- PAGE CONTENT BEGINS -->
                        <form action="{{route($base_route.'.store')}}" class="form-horizontal" role="form" id="validation-form" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Title </label>

                                <div class="col-sm-9">
                                    <input type="text" name="title" id="" placeholder="Title" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            {{--<div class="form-group">--}}
                                {{--<label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Slug </label>--}}

                                {{--<div class="col-sm-9">--}}
                                    {{--<input type="text" name="slug" id="" placeholder="Title" class="col-xs-10 col-sm-5">--}}
                                {{--</div>--}}
                            {{--</div>--}}

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Image</label>

                                <div class="col-sm-9">
                                    <input type="file" name="image" id="" placeholder="Image" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Writer</label>

                                <div class="col-sm-9">
                                    <input type="text" name="writer" id="" placeholder="Writer name" class="col-xs-10 col-sm-5">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Short description</label>

                                <div class="col-sm-9">
                                    <textarea type="text" rows="4" cols="4" name="short_desc" id="" placeholder="Description" class="col-xs-10 col-sm-5"></textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Detail description</label>

                                <div class="col-sm-9">
                                    <textarea type="text" rows="8" cols="8" name="detail_desc" id="" placeholder="Description" class="col-xs-10 col-sm-5 textarea"></textarea>
                                </div>
                            </div>

                            <div class="form-group date-picker">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Publish date</label>

                                <div class="col-sm-9">
                                    <input type="date" name="date" id="" placeholder="dd/mm/yyyy" class="col-xs-10 col-sm-5 ">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Status</label>

                                <div class="col-sm-9">
                                    <div class="radio">
                                        <label>
                                            <input name="form-field-radio" type="radio" class="ace" />
                                            <span class="lbl"> Active</span>
                                        </label>
                                    </div>

                                    <div class="radio">
                                        <label>
                                            <input name="form-field-radio" type="radio" class="ace" />
                                            <span class="lbl"> Inactive</span>
                                        </label>
                                    </div>
                                </div>
                            </div>


                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">
                                        <i class="ace-icon fa fa-check bigger-110"></i>
                                        Submit
                                    </button>

                                    &nbsp; &nbsp; &nbsp;
                                    <button class="btn" type="reset">
                                        <i class="ace-icon fa fa-undo bigger-110"></i>
                                        Reset
                                    </button>
                                </div>
                            </div>
                        </form>

                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->


    @endsection

@section('js')

    <script src="{{asset('admin-panel/assets/js/jquery.validate.min.js')}}"></script>
    <script src="{{asset('admin-panel/assets/css/bootstrap-datepicker3.min.css')}}"></script>

    <script src="{{asset('vendor/unisharp/laravel-ckeditor/ckeditor.js')}}"></script>
    <script src="{{asset('vendor/unisharp/laravel-ckeditor/adapters/jquery.js')}}"></script>
    <script>
        // $('textarea').ckeditor();
        $('.textarea').ckeditor(); // if class is prefered.
    </script>

    <script>
      $(document).ready(function () {
          $('#validation-form').validate();
      })

      $('.date-picker').datepicker({
          autoclose: true,
          todayHighlight: true
      })
  </script>
    @endsection

resources/views/admin/news/edit.blade.php
@extends('admin.layout.master')

@section('content')

    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">Home</a>
                    </li>

                    <li>
                        <a href="#">News</a>
                    </li>
                    <li class="active">Edit form</li>
                </ul><!-- /.breadcrumb -->

                <div class="nav-search" id="nav-search">
                    <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
                    </form>
                </div><!-- /.nav-search -->
            </div>

            <div class="page-content">
                <div class="page-header">
                    <h1>
                        Category
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                            Edit form
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                    @endif
                        <!-- PAGE CONTENT BEGINS -->
                        <form action="{{route('admin.news.update',$news->id)}}" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('POST')
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Title </label>

                                <div class="col-sm-9">
                                    <input type="text" name="title" id="" class="col-xs-10 col-sm-5" value="{{$news->title}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Image </label>

                                <div class="col-sm-9">
                                    <input type="file" name="image" id="" class="col-xs-10 col-sm-5" value="{{$news->image}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Writer </label>

                                <div class="col-sm-9">
                                    <input type="text" name="writer" id="" class="col-xs-10 col-sm-5" value="{{$news->writer}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Short description </label>

                                <div class="col-sm-9">
                                    <textarea type="text" rows="4" cols="4" name="short_desc" id="" class="col-xs-10 col-sm-5" value="">{{$news->short_desc}}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Detail description </label>

                                <div class="col-sm-9">
                                    <textarea type="text" rows="8" cols="8" name="detail_desc" id="" class="col-xs-10 col-sm-5" value="">{{$news->detail_desc}}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Publish date </label>

                                <div class="col-sm-9">
                                    <input type="date" name="date" id="" class="col-xs-10 col-sm-5" value="{{$news->date}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Status </label>

                                <div class="col-sm-9">
                                    <input type="text" name="status" id="" placeholder="Status" class="col-xs-10 col-sm-5" value="{{$news->status}}">
                                </div>
                            </div>

                            <div class="clearfix form-actions">
                                <div class="col-md-offset-3 col-md-9">
                                    <button class="btn btn-info" type="submit">
                                        <i class="ace-icon fa fa-check bigger-110"></i>
                                        Submit
                                    </button>

                                    &nbsp; &nbsp; &nbsp;
                                    <button class="btn" type="reset">
                                        <i class="ace-icon fa fa-undo bigger-110"></i>
                                        Reset
                                    </button>
                                </div>
                            </div>
                        </form>

                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->


    @endsection

resources/views/admin/news/test.blade.php
<ul class="nav nav-list">
        <li {!! request()->is('admin/dashboard')?'class="active"':'' !!}>
            <a href="{{route('admin.dashboard')}}">
                <i class="menu-icon fa fa-tachometer"></i>
                <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
        </li>

        <li class="">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-desktop"></i>
                <span class="menu-text">
								UI &amp; Elements
							</span>

                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
                <li class="">
                    <a href="#" class="dropdown-toggle">
                        <i class="menu-icon fa fa-caret-right"></i>

                        Layouts
                        <b class="arrow fa fa-angle-down"></b>
                    </a>

                    <b class="arrow"></b>

                    <ul class="submenu">
                        <li class="">
                            <a href="top-menu.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Top Menu
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="two-menu-1.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Two Menus 1
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="two-menu-2.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Two Menus 2
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="mobile-menu-1.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Default Mobile Menu
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="mobile-menu-2.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Mobile Menu 2
                            </a>

                            <b class="arrow"></b>
                        </li>

                        <li class="">
                            <a href="mobile-menu-3.html">
                                <i class="menu-icon fa fa-caret-right"></i>
                                Mobile Menu 3
                            </a>

                            <b class="arrow"></b>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul><!-- /.nav-list -->