routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin/', 'as'=>'admin.','middleware' => ['auth','auth-custom']],function (){

    Route::get('dashboard',              ['as'=>'dashboard','uses' => 'Admin\DashboardController@index']);

    Route::get('user',                   ['as'=>'user','uses' => 'Admin\UserController@index']);
    Route::get('user/add',               ['as'=>'user.add','uses' => 'Admin\UserController@add']);
    Route::post('user/store',            ['as'=>'user.store','uses' => 'Admin\UserController@store']);
    Route::get('user/edit/{id}',         ['as'=>'user.edit','uses' => 'Admin\UserController@edit']);
    Route::post('user/update/{id}',      ['as'=>'user.update','uses' => 'Admin\UserController@update']);
    Route::get('user/delete/{id}',       ['as'=>'user.delete','uses' => 'Admin\UserController@delete']);
    Route::get('user/password-reset',    ['as'=>'user.password-reset','uses' => 'Admin\UserController@passwordReset']);
    Route::post('user/password-reset',   ['as'=>'user.password-reset.update','uses' => 'Admin\UserController@passwordUpdate']);

    Route::get('site-profile/edit',      ['as'=>'site-profile.edit','uses' => 'Admin\SiteProfileController@edit']);
    Route::post('site-profile/update',   ['as'=>'site-profile.update','uses' => 'Admin\SiteProfileController@update']);

    Route::get('category',                   ['as'=>'category','uses' => 'Admin\CategoryController@index']);
    Route::get('category/add',               ['as'=>'category.add','uses' => 'Admin\CategoryController@add']);
    Route::post('category/store',            ['as'=>'category.store','uses' => 'Admin\CategoryController@store']);
    Route::get('category/edit/{id}',         ['as'=>'category.edit','uses' => 'Admin\CategoryController@edit']);
    Route::post('category/update/{id}',      ['as'=>'category.update','uses' => 'Admin\CategoryController@update']);
    Route::get('category/delete/{id}',       ['as'=>'category.delete','uses' => 'Admin\CategoryController@delete']);

    Route::get('news',                   ['as'=>'news','uses' => 'Admin\NewsController@index']);
    Route::get('news/add',               ['as'=>'news.add','uses' => 'Admin\NewsController@add']);
    Route::post('news/store',            ['as'=>'news.store','uses' => 'Admin\NewsController@store']);
    Route::get('news/edit/{id}',         ['as'=>'news.edit','uses' => 'Admin\NewsController@edit']);
    Route::post('news/update/{id}',      ['as'=>'news.update','uses' => 'Admin\NewsController@update']);
    Route::get('news/delete/{id}',       ['as'=>'news.delete','uses' => 'Admin\NewsController@delete']);
});
// part 8 1.45.12 mins completed
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/includes/head.blade.php
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>Dashboard - Ace Admin</title>

    <meta name="description" content="overview &amp; stats" />
    <link rel="stylesheet" href="{{asset('admin-panel/assets/css/bootstrap.min.css')}}" />
    <link rel="stylesheet" href="{{asset('admin-panel/assets/font-awesome/4.5.0/css/font-awesome.min.css')}}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

    <!-- bootstrap & fontawesome -->

    <!-- page specific plugin styles -->
    <link rel="stylesheet" href="{{asset('admin-panel/assets/css/fonts.googleapis.com.css')}}" />

    <!-- text fonts -->
    <link rel="stylesheet" href="{{asset('admin-panel/assets/css/ace.min.css')}}" class="ace-main-stylesheet" id="main-ace-style" />

    <!-- ace styles -->
    <link rel="stylesheet" href="{{asset('admin-panel/assets/css/ace-part2.min.css')}}" class="ace-main-stylesheet" />
    <link rel="stylesheet" href="{{asset('admin-panel/assets/css/ace-skins.min.css')}}" />
    <link rel="stylesheet" href="{{asset('admin-panel/assets/css/ace-rtl.min.css')}}" />

    <!--[if lte IE 9]>
    <![endif]-->
    <link rel="stylesheet" href="{{asset('admin-panel/assets/css/ace-ie.min.css')}}" />

    <!--[if lte IE 9]>
    <![endif]-->

    <!-- inline styles related to this page -->

    <!-- ace settings handler -->
    <script src="{{asset('admin-panel/assets/js/ace-extra.min.js')}}"></script>

    <!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

    <!--[if lte IE 8]>
    <script src="{{asset('admin-panel/assets/js/html5shiv.min.js')}}"></script>
    <script src="{{asset('admin-panel/assets/js/respond.min.js')}}"></script>
    <![endif]-->
</head>

@yield('css')

resources/views/admin/includes/sidebar.blade.php
<div id="sidebar" class="sidebar                  responsive                    ace-save-state">
    <script type="text/javascript">
        try{ace.settings.loadState('sidebar')}catch(e){}
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
                <i class="ace-icon fa fa-signal"></i>
            </button>

            <button class="btn btn-info">
                <i class="ace-icon fa fa-pencil"></i>
            </button>

            <button class="btn btn-warning">
                <i class="ace-icon fa fa-users"></i>
            </button>

            <button class="btn btn-danger">
                <i class="ace-icon fa fa-cogs"></i>
            </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div><!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
        <li {!! request()->is('admin/dashboard')?'class="active"':'' !!}>
            <a href="{{route('admin.dashboard')}}">
                <i class="menu-icon fa fa-tachometer"></i>
                <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
        </li>

        <li {!! request()->is('admin/user*')?'class="active open"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-desktop"></i>
                <span class="menu-text">
								User manager
							</span>

                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
                <li {!! request()->is('admin/user')?'class="active"':'' !!}>
                    <a href="{{route('admin.user')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Lists
                    </a>

                    <b class="arrow"></b>
                </li>

                <li {!! request()->is('admin/user/add')?'class="active"':'' !!}>
                    <a href="{{route('admin.user.add')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                       Add
                    </a>

                    <b class="arrow"></b>
                </li>

            </ul>
        </li>
        <li {!! request()->is('admin/category*')?'class="active open"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-desktop"></i>
                <span class="menu-text">
								Category manager
							</span>

                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
                <li {!! request()->is('admin/category')?'class="active"':'' !!}>
                    <a href="{{route('admin.category')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Lists
                    </a>

                    <b class="arrow"></b>
                </li>

                <li {!! request()->is('admin/category/add')?'class="active"':'' !!}>
                    <a href="{{route('admin.category.add')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Add
                    </a>

                    <b class="arrow"></b>
                </li>

            </ul>
        </li>

        <li {!! request()->is('admin/news*')?'class="active open"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-desktop"></i>
                <span class="menu-text">
								News manager
							</span>

                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
                <li {!! request()->is('admin/news')?'class="active"':'' !!}>
                    <a href="{{route('admin.news')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Lists
                    </a>

                    <b class="arrow"></b>
                </li>

                <li {!! request()->is('admin/news/add')?'class="active"':'' !!}>
                    <a href="{{route('admin.news.add')}}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Add
                    </a>

                    <b class="arrow"></b>
                </li>

            </ul>
        </li>
    </ul><!-- /.nav-list -->

    <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
        <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
    </div>
</div>